Repository GianMewes/SciFiPi, pull requests merged in 2021-05, with the labels that each got.

#65 Gian mewes patch 3
  Pipeline_Abstract.wsd
Labels: hotfix

#66 Gian mewes patch 4
  data/.gitkeep
  data/example/.gitkeep
  data/real/.gitkeep
  data/signal1.csv
  data/signal2.csv
  data/signal3.csv
Labels: hotfix

#62 Add license 1
  LICENSE
Labels: enhancement

#68 Refactoring/prepare for release
  LICENSE
  setup.cfg
  setup.py
  src/SciFiPi.py
  src/SciFiPi/FilterBuilder.py
  src/SciFiPi/PreFilterBuilder.py
  src/SciFiPi/__init__.py
  src/SciFiPi/cleaners/FormatData.py
  src/SciFiPi/cleaners/__init__.py
  src/SciFiPi/filters/DecimalShiftFilter.py
  src/SciFiPi/filters/LagFilter.py
  src/SciFiPi/filters/NoiseFilter.py
  src/SciFiPi/helper/__init__.py
  src/SciFiPi/preFilters/DuplicateFilter.py
  src/SciFiPi/preFilters/EquiDistanceFilter.py
  src/SciFiPi/preFilters/FillTimestampsFilter.py
  src/SciFiPi/preFilters/FixTimezoneFilter.py
  src/SciFiPi/preFilters/ImputationFilter.py
  src/SciFiPi/preFilters/__init__.py
Labels: bug
